# -*- coding: utf-8 -*-
"""day11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQSfEpafFfbOfRoXgU8ePz4Jka_SJ491
"""

import pandas as pd

df = pd.DataFrame({
    'Team':['India','India','Australia','Australia','India'],
    'Player':['Virat','Rohit','Smith','Warner','Hardik'],
    'Runs':[80,60,70,50,65]
})

print(df)

#using groupby
print("Original Data:")
print(df)
grouped = df.groupby('Player')['Runs'].sum()

print("\nTotal Runs by Each Player:")
print(grouped)
display(grouped)

# Group by single column 'Player'
grouped = df.groupby('Player')['Runs'].sum()

print("\nTotal Runs by Player:")
print(grouped)

import pandas as pd

# Sample Data
data = {
    'Team': ['India', 'India', 'Australia', 'Australia', 'India'],
    'Role': ['Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler'],
    'Runs': [80, 20, 70, 15, 30]
}

df = pd.DataFrame(data)

print("Original Data:")
print(df)

# Group by Team and Role
grouping = df.groupby(['Team', 'Role'])['Runs'].sum()

print("\nRuns by Team and Role:")
print(grouping)

# Apply aggregation functions
aggregated_data = df.groupby(['Team', 'Role']).agg(
    Total_Runs=('Runs', 'sum'),
    Average_Runs=('Runs', 'mean'),
    Match_Count=('Runs', 'count')
)
print(aggregated_data)

df['Rank_Within_Team'] = df.groupby('Team')['Runs'].transform(
    lambda x: x.rank(ascending=False)
)

print(df)

import pandas as pd
data = {
    'Player': ['Virat', 'Rohit', 'Gill', 'Smith', 'Warner'],
    'Team': ['India', 'India', 'India', 'Australia', 'Australia'],
    'Runs': [80, 60, 90, 70, 50]
}
df = pd.DataFrame(data)
# Filter teams where average runs >= 70
filtered_df = df.groupby('Team').filter(
    lambda x: x['Runs'].mean() >= 70
)
print(filtered_df)

import pandas as pd
# Create DataFrame for Dataset 1
data1 = [
    [1, 'Virat', 35],
    [2, 'Rohit', 37],
    [3, 'Gill', 25],
    [4, 'Rahul', 32],
    [5, 'Hardik', 31],
    [6, 'Jadeja', 36]
]
df1 = pd.DataFrame(data1, columns=['ID', 'Name', 'Age'])
# Create DataFrame for Dataset 2
data2 = [
    [1, 'Male', 25000],
    [2, 'Male', 42000],
    [3, 'Male', 38000],
    [4, 'Male', 45000],
    [5, 'Male', 50000],
    [6, 'Male', 47000]
]
df2 = pd.DataFrame(data2, columns=['ID', 'Gender', 'Salary'])
# Perform an Inner Merge on the 'ID' column
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print(merged_df)

#left merge
df2 = pd.DataFrame(data2, columns=['ID', 'Gender', 'Salary'])

merged_df = pd.merge(df1, df2, on='ID', how='left')

print(merged_df)

#Right merge
merged_df = pd.merge(df1, df2, on='ID', how='right')

print(merged_df)

import pandas as pd
data1 = [
    [1, 'India', 'Virat'],
    [2, 'India', 'Rohit'],
    [3, 'Australia', 'Smith']
]
df1 = pd.DataFrame(data1, columns=['ID', 'Country', 'Name'])
data2 = [
    [1, 'India', 25000],
    [2, 'India', 42000],
    [3, 'Australia', 38000]
]
df2 = pd.DataFrame(data2, columns=['ID', 'Country', 'Salary'])
merged_df = pd.merge(df1, df2, on=['ID', 'Country'], how='inner')
print(merged_df)

import pandas as pd

data1 = [
    [1, 'Virat', 35],
    [2, 'Rohit', 37],
    [3, 'Gill', 25]
]
df1 = pd.DataFrame(data1, columns=['ID', 'Name', 'Age'])
data2 = [
    [1, 'Male', 25000],
    [2, 'Male', 42000],
    [3, 'Male', 38000]
]
df2 = pd.DataFrame(data2, columns=['EmpID', 'Gender', 'Salary'])
merged_df = pd.merge(
    df1,
    df2,
    left_on='ID',
    right_on='EmpID',
    how='inner'
)
print(merged_df)

#pivot
import pandas as pd
data = {
    'Name': ['Raj', 'Priya', 'Aman'],
    'Course': ['Python', 'Java', 'Python'],
    'Marks': [85, 90, 78]
}
df = pd.DataFrame(data)
result = df.pivot(
    index='Name',
    columns='Course',
    values='Marks'
)
print(result)